package main

import (
	"context"
	"log"
	"net"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// UserService implements the gRPC user service
type UserService struct {
	UnimplementedUserServiceServer
}

// User represents a user entity
type User struct {
	Id    string
	Name  string
	Email string
}

// GetUser retrieves a user by ID
func (s *UserService) GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error) {
	if req.Id == "" {
		return nil, status.Error(codes.InvalidArgument, "user ID is required")
	}

	// Mock user data
	user := &User{
		Id:    req.Id,
		Name:  "John Doe",
		Email: "john@example.com",
	}

	return &UserResponse{
		User: user,
	}, nil
}

// CreateUser creates a new user
func (s *UserService) CreateUser(ctx context.Context, req *CreateUserRequest) (*UserResponse, error) {
	if req.Name == "" || req.Email == "" {
		return nil, status.Error(codes.InvalidArgument, "name and email are required")
	}

	user := &User{
		Id:    "generated-id",
		Name:  req.Name,
		Email: req.Email,
	}

	return &UserResponse{
		User: user,
	}, nil
}

// ListUsers returns a list of users
func (s *UserService) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	users := []*User{
		{Id: "1", Name: "John Doe", Email: "john@example.com"},
		{Id: "2", Name: "Jane Smith", Email: "jane@example.com"},
	}

	return &ListUsersResponse{
		Users: users,
	}, nil
}

// UpdateUser updates an existing user
func (s *UserService) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UserResponse, error) {
	if req.Id == "" {
		return nil, status.Error(codes.InvalidArgument, "user ID is required")
	}

	user := &User{
		Id:    req.Id,
		Name:  req.Name,
		Email: req.Email,
	}

	return &UserResponse{
		User: user,
	}, nil
}

// DeleteUser deletes a user
func (s *UserService) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	if req.Id == "" {
		return nil, status.Error(codes.InvalidArgument, "user ID is required")
	}

	return &DeleteUserResponse{
		Success: true,
		Message: "User deleted successfully",
	}, nil
}

func main() {
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}

	grpcServer := grpc.NewServer(
		grpc.UnaryInterceptor(loggingInterceptor),
	)

	RegisterUserServiceServer(grpcServer, &UserService{})

	log.Println("gRPC server running on port :50051")
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}

// Logging interceptor
func loggingInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	log.Printf("gRPC method called: %s", info.FullMethod)
	resp, err := handler(ctx, req)
	if err != nil {
		log.Printf("gRPC method %s failed: %v", info.FullMethod, err)
	}
	return resp, err
}

// Proto definitions (normally generated from .proto files)
type GetUserRequest struct {
	Id string
}

type CreateUserRequest struct {
	Name  string
	Email string
}

type UpdateUserRequest struct {
	Id    string
	Name  string
	Email string
}

type DeleteUserRequest struct {
	Id string
}

type ListUsersRequest struct {
	Page     int32
	PageSize int32
}

type UserResponse struct {
	User *User
}

type ListUsersResponse struct {
	Users []*User
}

type DeleteUserResponse struct {
	Success bool
	Message string
}

// Unimplemented server (normally generated)
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func (UnimplementedUserServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv interface{}) {
	// Normally generated by protoc
}
